### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by ayy-bc** [ayy-bc/ayy-bc#12]
```[tasklist]
### Tasks
- [x] 4
- [x] 1
- [x] 2
- [x] 3
```

```[tasklist]
### Tasks
- [x] https://github.com/ayy-bc/ayy-bc/issues/13
- [x] 5
- [x] 7
- [ ] 8
- [ ] https://github.com/ayy-bc/ayy-bc/issues/4
- [ ] https://github.com/ayy-bc/ayy-bc/issues/9
```
